name: insurance_company_automation
description: Client.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_screenutil: ^5.5.4
  cached_network_image: ^3.2.3
  get: ^4.6.5
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  formz: ^0.4.1
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  sidebarx: ^0.14.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  grouped_list: ^5.1.2
  sqflite: ^2.2.1
  path: ^1.8.2
  path_provider: ^2.0.11
  sqflite_common: ^2.4.0+2
  sqflite_common_ffi: ^2.2.0+1
  grpc: ^3.1.0
  protobuf: ^2.1.0
  connectivity_plus: ^3.0.2
  custom_pop_up_menu: ^1.2.4
  blur: ^3.1.0
  get_it: ^7.2.0
  stream_transform: ^2.1.0
  internet_connection_checker: ^1.0.0+1
  async: ^2.9.0
  js: ^0.6.2
  flex_color_picker: ^3.0.0
  dio: ^4.0.6
  file_picker: ^5.2.4
  flutter_riverpod: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  freezed: ^2.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf

    - family: InterBlack
      fonts:
        - asset: assets/fonts/Inter-Black.ttf

    - family: InterBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf

    - family: InterExtraBold
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf

    - family: InterExtraLight
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf

    - family: InterLight
      fonts:
        - asset: assets/fonts/Inter-Light.ttf

    - family: InterMedium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf

    - family: InterRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

    - family: InterSemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf

    - family: InterThin
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
